<!-- Set CSS files -->
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/style.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/incidental.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/dough.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/view/parts/navbar.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/view/parts/footer.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/view/home.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/view/follow-up.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/view/contact.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/view/blog-single.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/view/testimonials.css'; ?>">
<link rel="stylesheet" href="<?php bloginfo('stylesheet_url'); ?>">

<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/bootstrap.css'; ?>">
<link rel="stylesheet" href="<?= get_stylesheet_directory_uri() . '/css/bootstrap.min.css'; ?>">


<!-- FONT AWESOME ICONS ETC -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">