<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Include the bootstrap css and meta links. -->
    <?php include 'css.phtml' ?>
    <?php include 'js.phtml' ?>

    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Pagina Titel -->
    <!--    <title>peardot</title>-->


    <?php wp_head(); ?>

</head>
<body>

<main id="contents">
    <!--Navbar-->
    <?php require_once 'navbar.phtml' ?>
    <!--Content-->
    <section class="content">