<!-- Set JS files -->
<script type="text/javascript" src="<?= get_stylesheet_directory_uri() . '/js/jquery-3.4.1.js'; ?>"></script>
<script type="text/javascript" src="<?= get_stylesheet_directory_uri() . '/js/jquery-3.4.1.min.js'; ?>"></script>
<script type="text/javascript" src="<?= get_stylesheet_directory_uri() . '/js/bootstrap.js'; ?>"></script>
<script type="text/javascript" src="<?= get_stylesheet_directory_uri() . '/js/bootstrap.min.js'; ?>"></script>

<script type="text/javascript" src="<?= get_stylesheet_directory_uri() . '/js/script.js'; ?>"></script>
<script type="text/javascript" src="<?= get_stylesheet_directory_uri() . '/js/navbar.js'; ?>"></script>

<script type="text/javascript" src="<?= get_stylesheet_directory_uri() . '/js/navbar-mega.js'; ?>"></script>
